name: Update Readme Actions
on:
  schedule:
    # Runs at 0am UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Badges - README
        uses: Adonis0219/badge-readme@main
        with:
          CREDLY_USER: "adonis0219"
